server:
  port: 8081
spring:
  application:
    name: initDB-AI
  ai:
    openai:
      api-key: ${AI_OPENAI_API-KEY}
      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
      chat:
        options:
          model: ${AI_OPENAI_CHAT_OPTIONS_MODEL:qwen-max}
          max-tokens: 512
          temperature: 0.1          # 降低随机性，让回答更确定
          presencePenalty: 0.2      # 降低存在惩罚，避免干扰模型聚焦
          frequencyPenalty: 0.2     # 防止模型重复啰嗦
      embedding:
        options:
          model: ${AI_OPENAI_EMBEDDING_OPTIONS_MODEL:text-embedding-v1}
    alibaba:
      mcp:
        nacos:
          namespace: public
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          register:
            enabled: false
            service-group: mcp-server       ## 指定分组名称
            service-name: db-mcp-server     ## 指定服务名称
            service-register: false
  thymeleaf:
    cache: false
logging:
  level:
    cn.fish: DEBUG
    com.alibaba.cloud.ai.graph: INFO
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
        server: DEBUG
## SQL Agent Configuration
database-agent:
  max-results: 10

