server:
  port: 8080
spring:
  application:
    name: initDB-AI
  ai:
    openai:
#      api-key: ${AI_DEEPSEEK_API_KEY:sk-bb31cab6a8ac4c04a4d74a9e8196a064}
      api-key: ${AI_DEEPSEEK_API_KEY:}
      base-url: ""
      chat:
        options:
          model:
  thymeleaf:
    cache: false
logging:
  level:
    cn.fish: DEBUG
    com.alibaba.cloud.ai.graph: DEBUG

## SQL Agent Configuration
database-agent:
  max-results: 10

